package main

type AutoGenerated struct {
	UsecaseName      string `json:"usecaseName"`
	ServiceCondition string `json:"serviceCondition"`
	Policyconditions []struct {
		Criteria string `json:"Criteria"`
		Action   string `json:"Action"`
	} `json:"Policyconditions"`
}

func main() {
}
